// Phase 7b-6 — F5 PR Report (Markdown).
//
// Cross-phase contract (briefing §5): the breaking-risks block sits
// between two HTML comment markers so Phase 8-5 can fill in detected
// risks without changing the Markdown layout. Snapshot test pins the
// marker shape; adjusting them is a breaking change for 8-5.
//
// Phase 10-7 — gitlab-mr variant. Different marker prefix
// (`vda-mr:`) so a webhook bot can target the right comments when both
// platforms are wired. Default stays 'github-pr' so existing snapshots
// and the vda-pr-report.yml workflow keep their contract.

export const BREAKING_RISKS_START = '<!-- vda:breaking-risks:start -->';
export const BREAKING_RISKS_END = '<!-- vda:breaking-risks:end -->';

export const BREAKING_RISKS_START_GITLAB = '<!-- vda-mr:breaking-risks:start -->';
export const BREAKING_RISKS_END_GITLAB = '<!-- vda-mr:breaking-risks:end -->';

export type PrReportFormat = 'github-pr' | 'gitlab-mr';

export interface ImpactSummary {
  summary: {
    changed: number;
    direct: number;
    transitive: number;
    endpoints: number;
    tables: number;
  };
  changedNodes: Array<{ id: string; label: string; kind: string }>;
  directImpact: Array<{ id: string; label: string; kind: string }>;
  transitiveImpact: Array<{ id: string; label: string; kind: string }>;
  affectedEndpoints: Array<{ id: string; label: string }>;
  affectedTables: Array<{ id: string; label: string }>;
}

export interface PrReportInput {
  changedFiles: string[];
  impact: ImpactSummary;
  ruleViolationDelta: number;
  /** Phase 8-5 fills this in. 7b emits the marker block with the
   *  placeholder string below when no detector is supplied. */
  breakingRisksMarkdown?: string;
  /** Phase 10-7 — output flavor. Defaults to 'github-pr'. */
  format?: PrReportFormat;
}

const PLACEHOLDER = '_(detected in Phase 8)_';

export function formatPrReport(input: PrReportInput): string {
  const { changedFiles, impact, ruleViolationDelta, breakingRisksMarkdown } = input;
  const format: PrReportFormat = input.format ?? 'github-pr';
  const startMarker = format === 'gitlab-mr' ? BREAKING_RISKS_START_GITLAB : BREAKING_RISKS_START;
  const endMarker = format === 'gitlab-mr' ? BREAKING_RISKS_END_GITLAB : BREAKING_RISKS_END;
  const lines: string[] = [];

  lines.push('## VDA Change Impact');
  lines.push('');
  lines.push(`- **Files changed**: ${changedFiles.length}`);
  lines.push(`- **Changed nodes**: ${impact.summary.changed}`);
  lines.push(`- **Direct dependents**: ${impact.summary.direct}`);
  lines.push(`- **Transitive dependents**: ${impact.summary.transitive}`);
  lines.push(`- **Affected API endpoints**: ${impact.summary.endpoints}`);
  lines.push(`- **Affected DB tables**: ${impact.summary.tables}`);
  lines.push(`- **Rule-violation delta**: ${ruleViolationDelta >= 0 ? '+' : ''}${ruleViolationDelta}`);

  if (impact.affectedEndpoints.length > 0) {
    lines.push('');
    lines.push('### Affected endpoints');
    for (const n of impact.affectedEndpoints.slice(0, 25)) {
      lines.push(`- \`${n.label}\``);
    }
    if (impact.affectedEndpoints.length > 25) {
      lines.push(`- _…and ${impact.affectedEndpoints.length - 25} more_`);
    }
  }

  if (impact.affectedTables.length > 0) {
    lines.push('');
    lines.push('### Affected DB tables');
    for (const n of impact.affectedTables.slice(0, 25)) {
      lines.push(`- \`${n.label}\``);
    }
    if (impact.affectedTables.length > 25) {
      lines.push(`- _…and ${impact.affectedTables.length - 25} more_`);
    }
  }

  // Phase 8-5 contract slot — DO NOT remove markers or change wording
  // outside the slot without updating the snapshot test on both sides.
  // Phase 10-7 — marker prefix swaps based on `format`; everything else
  // (heading, footer, body inside slot) is identical across formats.
  lines.push('');
  lines.push('### ⚠️ Breaking risks');
  lines.push(startMarker);
  lines.push(breakingRisksMarkdown ?? PLACEHOLDER);
  lines.push(endMarker);

  lines.push('');
  lines.push('<sub>Generated by [vda impact](https://github.com/corollazer0/vue_dependency_analyzer)</sub>');

  return lines.join('\n');
}
