import { describe, it, expect } from 'vitest';
import {
  formatPrReport,
  BREAKING_RISKS_START,
  BREAKING_RISKS_END,
  BREAKING_RISKS_START_GITLAB,
  BREAKING_RISKS_END_GITLAB,
  type ImpactSummary,
} from '../commands/prReport.js';

const fixtureImpact: ImpactSummary = {
  summary: { changed: 1, direct: 3, transitive: 7, endpoints: 2, tables: 1 },
  changedNodes: [{ id: 'a', label: 'UserService', kind: 'spring-service' }],
  directImpact: [
    { id: 'b', label: 'UserController', kind: 'spring-controller' },
    { id: 'c', label: 'UserRepository', kind: 'spring-service' },
    { id: 'd', label: 'UserMapper', kind: 'mybatis-mapper' },
  ],
  transitiveImpact: [],
  affectedEndpoints: [
    { id: 'e1', label: 'GET /api/users' },
    { id: 'e2', label: 'POST /api/users' },
  ],
  affectedTables: [{ id: 't1', label: 'users' }],
};

describe('formatPrReport (Phase 7b-6)', () => {
  it('matches the snapshot for a typical small change', () => {
    const md = formatPrReport({
      changedFiles: ['backend/src/main/java/UserService.java'],
      impact: fixtureImpact,
      ruleViolationDelta: 0,
    });
    expect(md).toMatchSnapshot();
  });

  it('emits the breaking-risks marker block with the Phase 8 placeholder when no detector supplies content', () => {
    const md = formatPrReport({
      changedFiles: [],
      impact: { ...fixtureImpact, summary: { changed: 0, direct: 0, transitive: 0, endpoints: 0, tables: 0 }, affectedEndpoints: [], affectedTables: [] },
      ruleViolationDelta: 0,
    });
    expect(md).toContain(BREAKING_RISKS_START);
    expect(md).toContain(BREAKING_RISKS_END);
    // Marker block must contain the placeholder string between the tags.
    const start = md.indexOf(BREAKING_RISKS_START);
    const end = md.indexOf(BREAKING_RISKS_END);
    const inner = md.slice(start + BREAKING_RISKS_START.length, end).trim();
    expect(inner).toBe('_(detected in Phase 8)_');
  });

  // Phase 10-7 — gitlab-mr format swaps the marker prefix; everything else stays.
  it('format=gitlab-mr swaps the breaking-risks markers but keeps all other content', () => {
    const githubMd = formatPrReport({
      changedFiles: ['backend/src/main/java/UserService.java'],
      impact: fixtureImpact,
      ruleViolationDelta: 0,
      format: 'github-pr',
    });
    const gitlabMd = formatPrReport({
      changedFiles: ['backend/src/main/java/UserService.java'],
      impact: fixtureImpact,
      ruleViolationDelta: 0,
      format: 'gitlab-mr',
    });
    expect(gitlabMd).toContain(BREAKING_RISKS_START_GITLAB);
    expect(gitlabMd).toContain(BREAKING_RISKS_END_GITLAB);
    expect(gitlabMd).not.toContain(BREAKING_RISKS_START);
    expect(gitlabMd).not.toContain(BREAKING_RISKS_END);
    // Heading + footer unchanged.
    expect(gitlabMd).toContain('### ⚠️ Breaking risks');
    expect(gitlabMd).toContain('Generated by [vda impact]');
    // Body identical except the marker swap.
    const swapped = githubMd
      .replace(BREAKING_RISKS_START, BREAKING_RISKS_START_GITLAB)
      .replace(BREAKING_RISKS_END, BREAKING_RISKS_END_GITLAB);
    expect(gitlabMd).toBe(swapped);
  });

  it('default format keeps the github-pr markers (back-compat)', () => {
    const md = formatPrReport({
      changedFiles: [],
      impact: { ...fixtureImpact, summary: { changed: 0, direct: 0, transitive: 0, endpoints: 0, tables: 0 }, affectedEndpoints: [], affectedTables: [] },
      ruleViolationDelta: 0,
    });
    expect(md).toContain(BREAKING_RISKS_START);
    expect(md).not.toContain(BREAKING_RISKS_START_GITLAB);
  });

  it('lets a Phase 8-style detector fill the marker slot without changing surrounding markdown', () => {
    const md = formatPrReport({
      changedFiles: ['backend/src/main/java/UserDto.java'],
      impact: fixtureImpact,
      ruleViolationDelta: 1,
      breakingRisksMarkdown: '- B1: removed field `UserDto#email` (was used by 3 callers)',
    });
    const start = md.indexOf(BREAKING_RISKS_START);
    const end = md.indexOf(BREAKING_RISKS_END);
    const inner = md.slice(start + BREAKING_RISKS_START.length, end).trim();
    expect(inner).toContain('B1: removed field');
    // Outside-the-marker content unchanged.
    expect(md).toContain('### ⚠️ Breaking risks');
    expect(md).toContain('Generated by [vda impact]');
  });
});
